# Generated by Django 6.1.1 on 2026-09-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icu_beds', models.IntegerField(default=10)),
                ('status', models.CharField(default='Optimal', max_length=50)),
            ],
        ),
    ]
